### ISSUE TITLE
How to generate high resolution images

### ISSUE THREAD

**Issue by jerrymatjila** [VinAIResearch/CREPS#1]
Thanks for the paper and the code. 
Kindly share coding guidelines of using a CREPS model trained on 512×512 images to generate near-realistic images at higher resolution. Lets say 1024x1024

**Comment by thuanz123** [comment]
Hi @jerrymatjila, sorry for my late reply. With the latest update, you now can generate images at any size (larger than 0 of course). For example:

`python gen_images.py --outdir=out --trunc=0.7 --seeds=600 --network=creps-ffhq-512x512.pkl --scale=2`

This command will produce an image at resolution 1024x1024

**Comment by thuanz123** [comment]
Apart from scaling, you can manipulate the variable "G.synthesis.b4.input.coords" to get your desired geometric transformation like translation, rotation, or distortion

**Comment by jerrymatjila** [comment]
Thanks
