### ISSUE TITLE
How to cal metrics on FFHQ1024x1024?

### ISSUE THREAD

**Issue by FerryHuang** [VinAIResearch/CREPS#2]
Thanks for providing all these clear guides. However I'm stucked with the metrics calculation on FFHQ1024x1024. Following the data preparation I run dataset_tool.py to generate a ffhq-1024x1024.zip using downloaded FFHQ1024x1024(around 90G so I confirm it's right 1024 ver.). Then I just call cal_metrics.py with ckpt creps-ffhq-512x512.pkl. I just got a error report like "OSError: Image files do not match the specified resolution". So where didi git it wrong?

**Comment by thuanz123** [comment]
Hi @FerryHuang. With the latest update, you now can calculate metrics with images at resolution different to the resolution of the generator. For example:

```.bash
python calc_metrics.py --metrics=fid50k_full --data=~/datasets/ffhq-1024x1024.zip --mirror=1 \
    --network=creps-ffhq-512x512.pkl --scale=2
```

This command will compute FID score between dataset at resolution 1024x1024 and images at resolution 1024x1024 generated by CREPS trained at resolution 512x512

**Comment by thuanz123** [comment]
More generally, you can use this command

```.bash
python calc_metrics.py --metrics=fid50k_full --data=~/datasets/ffhq-MxM.zip --mirror=1 \
    --network=creps-ffhq-NxN.pkl --scale=M/N
```

in case you need to compute metrics between a dataset at resolution MxM against CREPS trained at resolution NxN.
